<a href="https://colab.research.google.com/github/abernauer/Python-for-Data-Scientists-and-Engineers/blob/master/Python_for_Data_Scientists_%26_Engineers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Variables

In [58]:
import this

Notes on the zen of Python:
* Code that is readable is best
* Python is going to do what you said
* Python won't guess what you want to do
* Preferably there is only way to do something in Python, you should do it that way 


In [59]:
status = 'off'

In [60]:
# variables don't have type
# a letter is a bad variable name

b = 400
b = '400'

Everything in Python is an object that has:
* an identity (id)
* a type (type). Determines what operations object can perform.
* a value (mutable or immutable)
* reference count

In [61]:
id(b)

140707338392104

In [62]:
type(b)

str

In [63]:
b

'400'

In [64]:
import sys
sys.getrefcount(b)

18

In [65]:
# built-in "literals"
# string
name = "andrew \N{GRINNING FACE}" # literal
age_string = str(25) # using str constructor
name

'andrew 😀'

In [66]:
# number literals (constructor in parens)
age = 25 # integer literal (int)
cost =  5.5 # float literal (float)
loc = 1 + 0j # complex literal (complex)

In [67]:
# list literal 
names = [name, 'suzy', 'fred']
characters = list('aeiou') # constructor

In [68]:
characters

['a', 'e', 'i', 'o', 'u']

In [69]:
# tuple literal 
person = ('fred', 42, '123-432-0943', '123 North Street')
person2 = tuple(['susan', 43, '213-123-0987', '789 West Ave'])

In [70]:
person2

('susan', 43, '213-123-0987', '789 West Ave')

In [71]:
# dictionary
types = {'name' : 'string', 'age' : 'int'}
ages = dict(zip(['fred', 'suzy'], [20, 21]))
types2 = dict(name='string', age='int')

In [72]:
ages

{'fred': 20, 'suzy': 21}

In [73]:
types2

{'age': 'int', 'name': 'string'}

In [74]:
# set 
digits = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
unique_chars = set('lorem ipsum dolor')
unique_chars

{' ', 'd', 'e', 'i', 'l', 'm', 'o', 'p', 'r', 's', 'u'}

In [75]:
print(dir(__builtin__))

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EnvironmentError', 'Exception', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError', 'SyntaxWarning', 'SystemError

These are all in the built in namespace.

Lookup hierarchy:
* Local- function/method
* Enclosed - nested function/method
* Global
* Builtin
* Name error!


In [76]:
# name error
missing

NameError: ignored

naming 
* lowercase
* underscore_between_words
* don't start with numbers
* don't use names that are reserved or built in

#Math

In [ ]:
# +,-,*,/
42 + 10

In [ ]:
42 ** 100

** power operator

In [ ]:
57 % 2

In [ ]:
# number "tower" int, float, complex
3 + 4.5

In [ ]:
1 - (2+4j)

In [ ]:
# the secret life of Python objects
print(dir(42))

List of dunder methods or attributes of 42.

In [ ]:
help((42).bit_length)

In [ ]:
42.bit_length()

In [ ]:
(42).bit_length()

In [ ]:
bin(42)

In [ ]:
42 + 10 # calling or dispatching dunder add method

In [ ]:
# Python does this for us 
(42).__add__(10)

#Getting Help

? is not built in, but a feature of Juypter for getting help

In [ ]:
len?

In [ ]:
def adder(x, y):
    "Adds two values"
    return x + y

In [ ]:
adder?

?? Shows source code

In [ ]:
adder??

In [ ]:
help(adder)

In [ ]:
# hit enter alone to exit help
help()

dir function will list the attributes of an object

#Strings & Unicode

In [ ]:
name = 'paul'

In [ ]:
print(dir(name))

In [ ]:
name.upper?

In [ ]:
name.upper()

In [ ]:
name.title()

In [ ]:
name.find('au')

In [ ]:
name[0]

Retreiving value at index zero in name

In [ ]:
name[-1]

Shorthand for the following

In [ ]:
name[len(name) - 1]

Use negative indexing if you want something at the end.

In [ ]:
?len

In [ ]:
greeting = 'Hello \N{GRINNING FACE} \U0001f600 😀'
greeting

Unicode is not UTF8. Unicode is a mapping to names or characters. UTF8 is an encoding.

In [ ]:
# bytestring
greeting.encode('utf8')

The b inticates it's a bytestring a sequence of digits or characters

In [ ]:
greeting.encode('utf8').decode('utf8')

In [ ]:
paragraph = """Greetings,
Thank you for attending tonight.
Long-winded talk.
Goodbye!"""

Triple quotes allow for new lines in Python. """ typically used in docustrings.




In [ ]:
paragraph

In [ ]:
# F-strings (Python 3.6+)
minutes = 36 
paragraph = f"""Greetings {name.title()},
Thank you for attending tonight.
We will be here for {minutes/60:.2f} hours
Long-winded talk.
Goodbye {name}!"""
print(paragraph)

#Files


Old way to write to file with output stream:

In [ ]:
fout = open('names.csv', mode='w', encoding='utf8')
fout.write('name, age\n')
fout.write('jeff, 30\n')
fout.write('linda, 29\n')
fout.close()

Modern approach:

In [ ]:
# context manager also used in plotting and setting pandas parameters
with open('names.csv', mode='w', encoding='utf8') as fout:
    fout.write('name, age\n')
    fout.write('jeff, 30\n')
    fout.write('linda, 29\n')
# file is automatically closed when we dedent
fout.write('bad,42\n')

In [ ]:
print(dir(fout))

In [ ]:
help(fout.write)

In [ ]:
fout.write?

In [ ]:
with open('names.csv', encoding='utf8') as fin:
    data = fin.read()
data

Read the file as binary:

In [ ]:
with open('names.csv', mode='rb') as fin:
    one_byte = fin.read(1)
    ten_bytes = fin.read(10)
one_byte

In [ ]:
ten_bytes.decode('utf8')

In [ ]:
# careful with encoding
with open('unigreeting.txt', 'w', encoding='utf8') as fout:
    fout.write('Hello \N{GRINNING FACE}')

In [ ]:
greeting = open('unigreeting.txt', 'r', encoding='utf8').read()
greeting

In [ ]:
greeting = open('unigreeting.txt', 'r', encoding='windows_1252').read()
greeting

In [ ]:
greeting = open('unigreeting.txt', 'r', encoding='ascii').read()
greeting

In [ ]:
greeting.encode('windows_1252')

In [ ]:
greeting.encode('windows_1252').decode('utf8')

In [ ]:
import encodings
print(sorted(encodings.aliases.aliases))

#Lists

Typically, lists have items of the same type and they're mutable.

In [ ]:
names = ['john', 'paul', 'george']

In [ ]:
print(dir(names))

In [ ]:
names.append?

Append mutates the list in place and doesn't return a new list.

In [ ]:
names.append('ringo')

In [ ]:
names

In [ ]:
names.index('paul')

In [ ]:
names[1]

In [ ]:
names.__getitem__(1)

In [ ]:
names[1] = 'Paul'

In [ ]:
names

In [ ]:
'paul' in names

In [ ]:
names.__contains__('paul')

Lists generally hold things of the same type. In Python, lists are mutable.

# Slicing

Numpy and Pandas use slicing extensively.

In [ ]:
names

In [ ]:
# literal
last = ['lennon', 'mccartney', 'harrison', 'starr']

In [ ]:
enumerate(names)

In [ ]:
# index values - using constructor
list(enumerate(names))

In [ ]:
# negative index values
list((i - len(names), n) for i, n in enumerate(names))

In [ ]:
names[0]

In [ ]:
names[-1]

In [ ]:
# half-open interval
# - includes start index but not end
# - length = end - start
names[0:3]

Uses half open interval. Makes writing parallel implementations easier.

In [ ]:
names[:3]

In [ ]:
names

In [ ]:
names[2:]

In [ ]:
names[-2:]

In [ ]:
# create a copy
names2 = names[:]

In [ ]:
id(names2)

In [ ]:
id(names)

In [ ]:
names[0] is names2[0]

In [ ]:
names == names2

In [ ]:
names is names2

In [ ]:
names[::-1]

In [ ]:
list(range(10))

In [ ]:
list(range(10))[::3]

Step or the stride in slice.

In [ ]:
# also works with strings
filename = 'resume.pdf'
filename[:4]

In [ ]:
filename[4]

In [ ]:
filename[-3:]

In [ ]:
filename[::-1]

#Dictionaries

By word can look up a definition. Maps key:value pairs. Mod 30 operation tells you what bucket something falls in. It's an order one operation. Dictionaries are good for mapping operation aka changing column names.

In [ ]:
hash('name') % 30

In [ ]:
hash('name')

In [ ]:
hash([])

Example usage telling pandas the types of columns.

In [ ]:
# literal 
types = {'name': str, 'age': int, 'address': str}

Usings the constructor you need to pass valid literals.

In [ ]:
# constructor
types2 = dict(name=str, age=int, address=str)

In [ ]:
# index access
types['name']

Dictionaries like lists are mutable.

In [ ]:
# index assignment 
types['language'] = str

In [ ]:
types

In [ ]:
types['food']

In [ ]:
types.get('food', 'missing')

In [ ]:
types.get?

In [ ]:
print(dir(types))

In [ ]:
'food' in types

#Loopings & Comprehensions


In [ ]:
for name in names:
    print(name)

In [ ]:
for name in names:
    print(name.title())

Code smell in Python:

In [ ]:
names2 = []
for name in names:
    names2.append(name.title())
names2

To convert to a list comprehension, nest the for statement in your list without the : and add your fuction call or method.

List comprehensions are syntactic sugar.

In [ ]:
names2 = [name.title() for name in names]
names2

In [ ]:
types

When loop over a dictionary you loop over the keys. A dictionary is ordered in Python 3.6 and above.

In [ ]:
for t in types:
    print(t)

Code smell again.

In [ ]:
new_names = {}
for t in types:
    new_names[t] = t.title()
new_names

In [ ]:
new_names = {t: t.title() for t in types}
new_names

#Functions and Lambdas

Everything following the colon is indented and considered a block.

In [ ]:
def add(x, y):
  """This adds two values
  >>> add(2, 4)
  6
  """
  return x + y

In [ ]:
add(2, 4)

In [ ]:
add

In [ ]:
help(add)

In [ ]:
add?

In [ ]:
add??

Only on else available at the end of the conditional.

In [ ]:
# conditional aside
if name == 'paul':
    last = 'mccartney'
elif name == 'john':
    last = 'lennon'
else:
    last = 'doe'

In [ ]:
name, last

In [ ]:
def median(values):
    """
    Return the middle value  (if odd)
    or the average of the two middle values (if even)
    >>> median([1, 4, 5])
    4
    >>> median([0, 2, 6, 100])
    4.0
    """

    values = sorted(values)
    size = len(values)
    if size % 2 == 0:
        left = values[int(size/2-1)]
        right = values[int(size/2)]
        return (left + right)/2
    else:
        return values[int(size/2)]

In [ ]:
median

In [ ]:
median(range(100))

In [ ]:
median([100, 1, 200])

In [ ]:
# tuples
person = ('Paul', 'McCartney', 'Bass')

In [ ]:
type({person})

Tuples can be used to return multiple items from a function.

In [ ]:
def roots(val):
    return (val**.5, -(val**.5))

In [ ]:
roots(4)

Lambda functions returns an expression:

In [ ]:
adder2 = lambda x, y: x + y 
add(42, 10) == adder2(42, 10)

Max a variable and pass parameters.

In [ ]:
roots2 = lambda val: (val**.5, -(val**.5))

In [ ]:
roots2(64)

# Modules 

* Revisit this section 

#Classes and methods

Defs define the methods for our class.

In [ ]:
# Remember that everything is an object?
class MyInt:
    '''Docstring for MyInt'''
    def __init__(self, val):
        self.value = val
    
    def __add__(self, other):
        return MyInt(self.value + other)

    def __repr__(self):
        return f"MyInt({self.value})"

    def __str__(self):
        return f'(self.value)'

    def square(self):
        "Return the square of the value"
        return MyInt(self.value**2)

In [ ]:
MyInt

In [ ]:
num = MyInt(42)
num + 5 # calls.__add__the.__repr__methods

__init__ method is the constructor of our object.

In [ ]:
num.__add__(5)

In [ ]:
num - 5

In [ ]:
print(num) #calls .__str__

In [ ]:
num #calls .__repr__

In [ ]:
import pandas as pd


In [ ]:
pd.DataFrame??

In [ ]:
pd.DataFrame.__add__??

In [ ]:
pd.DataFrame.__repr__??

#Errors

In [ ]:
missing

Python is looking for a variable and can't find it.

In [ ]:
names.find('fred')

Attribute error trying to find something that doesn't exist.

In [ ]:
print(dir(names))

In [ ]:
names.index('fred')

In [ ]:
types['missing']

Exception handling:

In [ ]:
try:
    types['missing']
except KeyError:
    print('missing is not a key')

In [ ]:
# can also subclass and raise errors
raise KeyError('Key was missing')

# Numpy

In [78]:
# https://numpy.org/doc/stable/reference/
import numpy as np

Uses less memory than base python. 

In [79]:
digits = np.array(range(10))
digits

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.array?

Can have arbitrarly dimensioned arrays.

In [81]:
digits.shape

(10,)

In [82]:
# secret of numpy (there are not 10 Python integers under the arrray)
digits.dtype

dtype('int64')

In [83]:
np.log(digits)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [84]:
np.log(digits+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [85]:
np.sin(digits)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [86]:
len(dir(np))

620

In [87]:
digits.

SyntaxError: ignored

Done at the C level.

In [88]:
digits + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [89]:
# 2d 
nums = np.arange(100).reshape(20, 5)
nums

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [90]:
nums.transpose()

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75,
        80, 85, 90, 95],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76,
        81, 86, 91, 96],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77,
        82, 87, 92, 97],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78,
        83, 88, 93, 98],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79,
        84, 89, 94, 99]])

In [91]:
nums.mean()

49.5

In [92]:
nums.mean(axis=0)

array([47.5, 48.5, 49.5, 50.5, 51.5])

In [93]:
nums.mean(axis=1)

array([ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47., 52., 57., 62.,
       67., 72., 77., 82., 87., 92., 97.])

In [94]:
nums.mean(axis=1, keepdims=True)

array([[ 2.],
       [ 7.],
       [12.],
       [17.],
       [22.],
       [27.],
       [32.],
       [37.],
       [42.],
       [47.],
       [52.],
       [57.],
       [62.],
       [67.],
       [72.],
       [77.],
       [82.],
       [87.],
       [92.],
       [97.]])

Goes across the columns.

In [95]:
#3d
b = np.arange(70).reshape(7,5,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69]]])

In [96]:
b.mean(axis=0)

array([[30., 31.],
       [32., 33.],
       [34., 35.],
       [36., 37.],
       [38., 39.]])

In [97]:
b.mean(axis=1)

array([[ 4.,  5.],
       [14., 15.],
       [24., 25.],
       [34., 35.],
       [44., 45.],
       [54., 55.],
       [64., 65.]])

In [98]:
b.mean(axis=2)

array([[ 0.5,  2.5,  4.5,  6.5,  8.5],
       [10.5, 12.5, 14.5, 16.5, 18.5],
       [20.5, 22.5, 24.5, 26.5, 28.5],
       [30.5, 32.5, 34.5, 36.5, 38.5],
       [40.5, 42.5, 44.5, 46.5, 48.5],
       [50.5, 52.5, 54.5, 56.5, 58.5],
       [60.5, 62.5, 64.5, 66.5, 68.5]])

# Slicing

In [99]:
nums

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [100]:
nums[0]

array([0, 1, 2, 3, 4])

Passing list to an index operation

In [101]:
nums[[0,5,10]]

array([[ 0,  1,  2,  3,  4],
       [25, 26, 27, 28, 29],
       [50, 51, 52, 53, 54]])

In [102]:
# first ten rows
nums[0:10]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [103]:
#first three columns
# all the rows and the first three columns not including 3
nums[:,0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22],
       [25, 26, 27],
       [30, 31, 32],
       [35, 36, 37],
       [40, 41, 42],
       [45, 46, 47],
       [50, 51, 52],
       [55, 56, 57],
       [60, 61, 62],
       [65, 66, 67],
       [70, 71, 72],
       [75, 76, 77],
       [80, 81, 82],
       [85, 86, 87],
       [90, 91, 92],
       [95, 96, 97]])

Per axis selector. 

#Boolean arrays

You can index with this Boolean array.

In [ ]:
nums % 2 == 0

In [ ]:
nums[nums %2 == 0]

In [ ]:
# select rows where sum is less than 100
nums.sum(axis=1)

In [ ]:
nums.sum(axis=1) < 100

In [ ]:
nums[nums.sum(axis=1)<100]

In [ ]:
# select columns where mean > 50
nums.mean(axis=0)

In [ ]:
nums.mean(axis=0) > 50

In [ ]:
nums[:, nums.mean(axis=0) > 50]

#Universal Functions

In [104]:
np.add(nums, 5)

array([[  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104]])

In [105]:
np.mod(nums, 2) # nums %2

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [106]:
np.log(nums + 1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738],
       [3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806],
       [3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945],
       [3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249],
       [3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301],
       [3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319],
       [4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456],
       [4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727],
       [4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524],
       [4.26267988, 4.27666612, 4.

In [107]:
# trig
np.sin(nums)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836],
       [-0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269],
       [-0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193],
       [ 0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265],
       [-0.26237485,  0.67022918,  0.98662759,  0.39592515, -0.55878905],
       [-0.99975517, -0.521551  ,  0.43616476,  0.99287265,  0.63673801],
       [-0.30481062, -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604],
       [ 0.82682868, -0.02655115, -0.8

In [108]:
nums

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [109]:
10 >> 1

5

In [110]:
#bit ops 
np.right_shift(nums, 1)

array([[ 0,  0,  1,  1,  2],
       [ 2,  3,  3,  4,  4],
       [ 5,  5,  6,  6,  7],
       [ 7,  8,  8,  9,  9],
       [10, 10, 11, 11, 12],
       [12, 13, 13, 14, 14],
       [15, 15, 16, 16, 17],
       [17, 18, 18, 19, 19],
       [20, 20, 21, 21, 22],
       [22, 23, 23, 24, 24],
       [25, 25, 26, 26, 27],
       [27, 28, 28, 29, 29],
       [30, 30, 31, 31, 32],
       [32, 33, 33, 34, 34],
       [35, 35, 36, 36, 37],
       [37, 38, 38, 39, 39],
       [40, 40, 41, 41, 42],
       [42, 43, 43, 44, 44],
       [45, 45, 46, 46, 47],
       [47, 48, 48, 49, 49]])

In [111]:
nums >> 1

array([[ 0,  0,  1,  1,  2],
       [ 2,  3,  3,  4,  4],
       [ 5,  5,  6,  6,  7],
       [ 7,  8,  8,  9,  9],
       [10, 10, 11, 11, 12],
       [12, 13, 13, 14, 14],
       [15, 15, 16, 16, 17],
       [17, 18, 18, 19, 19],
       [20, 20, 21, 21, 22],
       [22, 23, 23, 24, 24],
       [25, 25, 26, 26, 27],
       [27, 28, 28, 29, 29],
       [30, 30, 31, 31, 32],
       [32, 33, 33, 34, 34],
       [35, 35, 36, 36, 37],
       [37, 38, 38, 39, 39],
       [40, 40, 41, 41, 42],
       [42, 43, 43, 44, 44],
       [45, 45, 46, 46, 47],
       [47, 48, 48, 49, 49]])

In [112]:
# logic
np.logical_and(nums, nums % 2 == 0)

array([[False, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [113]:
# comparison 
np.greater(nums, 10)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [114]:
# floating point 
np.ceil(nums/3)

array([[ 0.,  1.,  1.,  1.,  2.],
       [ 2.,  2.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  5.,  5.],
       [ 5.,  6.,  6.,  6.,  7.],
       [ 7.,  7.,  8.,  8.,  8.],
       [ 9.,  9.,  9., 10., 10.],
       [10., 11., 11., 11., 12.],
       [12., 12., 13., 13., 13.],
       [14., 14., 14., 15., 15.],
       [15., 16., 16., 16., 17.],
       [17., 17., 18., 18., 18.],
       [19., 19., 19., 20., 20.],
       [20., 21., 21., 21., 22.],
       [22., 22., 23., 23., 23.],
       [24., 24., 24., 25., 25.],
       [25., 26., 26., 26., 27.],
       [27., 27., 28., 28., 28.],
       [29., 29., 29., 30., 30.],
       [30., 31., 31., 31., 32.],
       [32., 32., 33., 33., 33.]])

Avoid for loops with Numpy arrays and default to ufuncs.